Fix BOOT_FROM_* expressions.
We can't check if the address of a variable is zero because gcc isn't stupid:
systems/tests/tests.c:352: error: the address of '__boot_from_samba__' will never be NULL.